# vim laybook_sample.yml

- hosts: oreo
  tasks:
    - include: tasks/included.yml
      vars:
        general_packages: iperf3
    - include: tasks/included.yml
      vars:
        general_packages: lshw
    - include: tasks/included.yml
      vars:
        general_packages: cockpit
    - include: tasks/included.yml
      vars:
        general_packages: httpd
- include: yml/httpd.yml

# ==================================================

# vim yml/httpd.yml
- hosts: oreo
  tasks:
  - name: httpd is installed
    yum: name=httpd state=installed
  - name: httpd is running and enabled
    service: name=httpd state=started enabled=yes

# ansible oreo -m shell -a "yum -y autoremove cockpit lshw iperf3 httpd"