- hosts: oreo
  tasks:
  - name: Test Task
    file: path=/root/test1.conf state=touch owner=root group=root mode=0600


# 実行コマンド
# # ansible-playbook plyabook_sample.yml

# 確認コマンド
# ansible oreo -m command -a "ls -al /root"