---
## Firewallのポート許可
- name: check_install / Allow ports for firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ mariadb_firewalld_port }}"

## 不要なパッケージのアンインストール
- name: check_install / Remove current packages
  yum:
    name: mariadb-libs
    state: absent
