---
## MariaDB 設定の配備
- name: configure / Setup configure file
  template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes

## MariaDB の全停止
- name: configure / Stop all MariaDB for initialization
  systemd:
    name: mysql
    state: stopped

####### block の開始 #######
- name: configure / Start MariaDB Galera Master node
  block:

## マスターノードの起動
  - name: configure / Bootstrap first MariaDB Galera Cluster node
    command: galera_new_cluster
    args:
      creates: "/var/lib/mysql/{{ ansible_host }}.pid"

## マスターノードの起動確認
  - name: configure / Wait for bootstrapping first MariaDB
    wait_for:
      host: "{{ ansible_default_ipv4.address }}"
      port: 3306
      delay: 5
      timeout: 60

## MariaDB のrootパスワード設定
  - name: configure / Change root password
    command: mysqladmin -u root password "{{ mariadb_root_pass }}"
    args:
      creates: "/var/lib/mysql/.changed_root_pass.lck"
    register: changed_root_pass

## root パスワード用ロックファイルの配備
  - name: configure / Setup flag file
    file:
      path: /var/lib/mysql/.changed_root_pass.lck
      state: touch
      mode: 0400
    when: changed_root_pass.changed

## SST ユーザーの作成
  - name: configure / Add maruser SST user
    mysql_user:
      login_password: "{{ mariadb_root_pass }}"
      name: "{{ mariadb_sst_user }}"
      password: "{{ mariadb_sst_pass }}"
      host: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
      priv: "*.*:RELOAD,LOCK TABLES,REPLICATION CLIENT"
      append_privs: yes

  run_once: true  ## blok 全体に適用されるパラメーター
####### block の終了 #######

## クラスタノードの起動
- name: configure / Start MariaDB Galera Cluster node
  systemd:
    name: mysql
    state: started

## クラスタノードの起動確認
- name: configure / Wait for starting MariaDB Galera Cluster node
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 3306
    delay: 5
    timeout: 60
