# 対象のホストを指定
- hosts: oreo
  # タスクの定義
  tasks:
  # Apacheのインストール
  - name: httpd is installed
    yum: name=httpd state=installed
  # 起動と自動起動の設定
  - name: httpd is running and enabled
    service: name=httpd state=started enabled=yes

# 起動確認コマンド
# ansible oreo -m shell -a "systemctl status httpd | head -3"