- hosts: test3.tabiya.local
  handlers:
  - name: oreo_httpd
    service: name=httpd state=restarted

  tasks:
  - name: httpd is installed
    yum: name=httpd state=installed

  - name: edit httpd_config 1:sername
    lineinfile: >
      dest=/etc/httpd/conf/httpd.conf
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
    with_items:
    - { regexp: '#ServerName www.example.com:80', line: 'ServerName 192.168.2.93:8080' }

  - name: edit httpd_config 2:listen chenge
    lineinfile: >
      dest=/etc/httpd/conf/httpd.conf
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
    with_items:
    - { regexp: 'Listen 80', line: 'Listen 8080' }

    notify: oreo_httpd
    tags: Edit_httpd_config