# vim laybook_sample.yml

- hosts: oreo
  tasks:
    - include: tasks/included.yml
      vars:
        general_packages: iperf3
    - include: tasks/included.yml
      vars:
        general_packages: lshw
    - include: tasks/included.yml
      vars:
        general_packages: cockpit
    - include: tasks/included.yml
      vars:
        general_packages: httpd

# ==================================================

# vim tasks/included.yml
- name: General packages are installed
  yum: name="{{ item }}" state=installed
  with_items:
    - "{{ general_packages }}"
  tags: General_Packages

# ansible oreo -m shell -a "yum -y autoremove cockpit lshw iperf3 httpd"